apiVersion: v1
kind: Secret
metadata:
  name: hive-oracle-etl-secret
  labels:
    app.kubernetes.io/name: hive-oracle-etl
type: Opaque
stringData:
  HIVE_USERNAME: "hive_reader"
  HIVE_PASSWORD: "change_me"
  ORACLE_USER: "APP_ETL"
  ORACLE_PASSWORD: "change_me"
